### PR TITLE
A few changes.

### PR DESCRIPTION
**Pull request by biziclop**
Enjoy.
No tests (yet).

### CODE REVIEW

**Review by miromannino — APPROVED** [review]

**Review by miromannino — COMMENTED** [review]
I will just remove justifyTooTallRowMargins for now.

**Comment by biziclop** [comment]
Of course, that was just an experimental feature for someone's issue. There may be more similar questionable modifications. :)

**Comment by miromannino** [comment]
Which one you think could be questionable? :)

**Comment by biziclop** [comment]
I couldn't know, they might be questionable only for other people. :)

**Pull request merged**
